# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TmdbMoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TmdbMoviesApp
	pod 'RxSwift'
	pod 'RxCocoa'

  target 'TmdbMoviesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TmdbMoviesAppUITests' do
    # Pods for testing
  end

end
